# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ndpreport.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fndpreport.proto\x12\x0cMIMO_Toolkit\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x03\n\tNDPReport\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x41SNR\x18\x02 \x03(\x01\x12\x34\n\x11steering_matrices\x18\x03 \x03(\x0b\x32\x19.MIMO_Toolkit.NDPReport.V\x12(\n\x03mac\x18\x04 \x01(\x0b\x32\x1b.MIMO_Toolkit.NDPReport.Mac\x12\x38\n\x0bmimocontrol\x18\x05 \x01(\x0b\x32#.MIMO_Toolkit.NDPReport.MIMOControl\x1a\x37\n\x03Mac\x12\n\n\x02RA\x18\x01 \x01(\x04\x12\n\n\x02TA\x18\x02 \x01(\x04\x12\x0b\n\x03SRC\x18\x03 \x01(\x04\x12\x0b\n\x03\x44ST\x18\x04 \x01(\x04\x1a\x31\n\x0bMIMOControl\x12\n\n\x02nc\x18\x01 \x01(\r\x12\n\n\x02nr\x18\x02 \x01(\r\x12\n\n\x02ng\x18\x03 \x01(\r\x1a#\n\x05\x63ompl\x12\x0c\n\x04real\x18\x01 \x01(\x01\x12\x0c\n\x04imag\x18\x02 \x01(\x01\x1aU\n\x01V\x12.\n\x07\x63ontent\x18\x01 \x03(\x0b\x32\x1d.MIMO_Toolkit.NDPReport.compl\x12\x0f\n\x07row_num\x18\x02 \x01(\x04\x12\x0f\n\x07\x63ol_num\x18\x03 \x01(\x04\x62\x06proto3')

_NDPREPORT = DESCRIPTOR.message_types_by_name['NDPReport']
_NDPREPORT_MAC = _NDPREPORT.nested_types_by_name['Mac']
_NDPREPORT_MIMOCONTROL = _NDPREPORT.nested_types_by_name['MIMOControl']
_NDPREPORT_COMPL = _NDPREPORT.nested_types_by_name['compl']
_NDPREPORT_V = _NDPREPORT.nested_types_by_name['V']
NDPReport = _reflection.GeneratedProtocolMessageType('NDPReport', (_message.Message,), {

    'Mac': _reflection.GeneratedProtocolMessageType('Mac', (_message.Message,), {
        'DESCRIPTOR': _NDPREPORT_MAC,
        '__module__': 'ndpreport_pb2'
        # @@protoc_insertion_point(class_scope:MIMO_Toolkit.NDPReport.Mac)
    })
    ,

    'MIMOControl': _reflection.GeneratedProtocolMessageType('MIMOControl', (_message.Message,), {
        'DESCRIPTOR': _NDPREPORT_MIMOCONTROL,
        '__module__': 'ndpreport_pb2'
        # @@protoc_insertion_point(class_scope:MIMO_Toolkit.NDPReport.MIMOControl)
    })
    ,

    'compl': _reflection.GeneratedProtocolMessageType('compl', (_message.Message,), {
        'DESCRIPTOR': _NDPREPORT_COMPL,
        '__module__': 'ndpreport_pb2'
        # @@protoc_insertion_point(class_scope:MIMO_Toolkit.NDPReport.compl)
    })
    ,

    'V': _reflection.GeneratedProtocolMessageType('V', (_message.Message,), {
        'DESCRIPTOR': _NDPREPORT_V,
        '__module__': 'ndpreport_pb2'
        # @@protoc_insertion_point(class_scope:MIMO_Toolkit.NDPReport.V)
    })
    ,
    'DESCRIPTOR': _NDPREPORT,
    '__module__': 'ndpreport_pb2'
    # @@protoc_insertion_point(class_scope:MIMO_Toolkit.NDPReport)
})
_sym_db.RegisterMessage(NDPReport)
_sym_db.RegisterMessage(NDPReport.Mac)
_sym_db.RegisterMessage(NDPReport.MIMOControl)
_sym_db.RegisterMessage(NDPReport.compl)
_sym_db.RegisterMessage(NDPReport.V)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _NDPREPORT._serialized_start = 67
    _NDPREPORT._serialized_end = 525
    _NDPREPORT_MAC._serialized_start = 295
    _NDPREPORT_MAC._serialized_end = 350
    _NDPREPORT_MIMOCONTROL._serialized_start = 352
    _NDPREPORT_MIMOCONTROL._serialized_end = 401
    _NDPREPORT_COMPL._serialized_start = 403
    _NDPREPORT_COMPL._serialized_end = 438
    _NDPREPORT_V._serialized_start = 440
    _NDPREPORT_V._serialized_end = 525
# @@protoc_insertion_point(module_scope)
